---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Upgrade all packages to current
      become: true
      community.general.pacman:
        upgrade: true
        update_cache: true
      changed_when: false

    - name: Remove /etc/arch-release to allow SteamOS detection
      become: true
      ansible.builtin.file:
        path: /etc/arch-release
        state: absent

    - name: Simulate SteamOS /etc/os-release
      become: true
      ansible.builtin.copy:
        content: |
          ID=steamos
          ID_LIKE=arch
          NAME="SteamOS"
          PRETTY_NAME="SteamOS"
          VERSION_ID="3.6"
          VERSION_CODENAME=holo
        dest: /etc/os-release
        mode: "0644"

    - name: Install curl and unzip (simulate SteamOS)
      become: true
      community.general.pacman:
        name:
          - curl
          - unzip
        state: present
