---
- name: Update pacman cache (Arch Linux)
  become: true
  community.general.pacman:
    update_cache: true
  changed_when: false

- name: Install dependencies (Arch Linux)
  become: true
  community.general.pacman:
    name:
      - zsh
      - git
      - fontconfig
      - unzip

- name: Set zsh shell path
  ansible.builtin.set_fact:
    zsh_shell_path: /usr/bin/zsh
