---
- name: Install dependencies (macOS)
  become: false
  community.general.homebrew:
    name:
      - zsh
      - git
    state: present

- name: Detect zsh path (macOS)
  become: false
  ansible.builtin.command: which zsh
  register: zsh_path_cmd
  changed_when: false

- name: Set zsh shell path
  ansible.builtin.set_fact:
    zsh_shell_path: "{{ zsh_path_cmd.stdout }}"
