---
- name: Update cache (Debian)
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install dependencies (Debian)
  become: true
  ansible.builtin.package:
    name:
      - zsh
      - git
      - fontconfig
      - unzip
    state: present

- name: Set zsh shell path
  ansible.builtin.set_fact:
    zsh_shell_path: /usr/bin/zsh
