---
- name: Update cache when Ubuntu
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'

- name: Update cache when Arch Linux
  become: true
  community.general.pacman:
    update_cache: true
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Ensure git is installed
  become: true
  ansible.builtin.package:
    name: git
    state: present
  tags: ["git"]

- name: Ensure zsh is installed
  become: true
  ansible.builtin.package:
    name: zsh
    state: present
  tags: ["zsh"]

- name: Create ~/.config/zsh directory
  become: false
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/zsh"
    state: directory
    mode: 0755
  tags: ["zsh"]

- name: Clone oh-my-zsh
  become: false
  ansible.builtin.git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ ansible_env.HOME }}/.config/zsh/oh-my-zsh"
    version: master
  tags: ["zsh"]

- name: Generate ~/.config/zsh/ files
  become: false
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.config/zsh/{{ item }}"
    mode: 0644
  with_items:
    - zshrc
    - zshenv
    - alias.zsh
    - export.zsh
    - functions.zsh
    - keybindings.zsh
    - chef.zsh
    - aws.zsh
    - python.zsh
    - ansible.zsh
  tags: ["zsh"]

- name: Link zshrc and zshenv
  become: false
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.config/zsh/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    state: link
    force: yes
  with_items:
    - zshrc
    - zshenv
  tags: ["zsh"]

- name: Set user shell to zsh
  ignore_errors: true
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  tags: ["zsh"]