---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: localhost
provisioner:
  name: ansible
  inventory:
    hosts:
      localhost:
        ansible_connection: local
verifier:
  name: ansible
