---
name: CICD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5
      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install uv
        run: pip3 install uv
      - name: Install test dependencies
        run: uv sync
      - name: Install Galaxy requirements
        run: uv run ansible-galaxy role install -r requirements.yml
      - name: Lint code
        run: uv run yamllint .
      - name: Ansible lint
        run: uv run ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: -d docker
          molecule_working_dir: .
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  steamdeck:
    name: Steam Deck
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: -d docker -s steamdeck
          molecule_working_dir: .
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5
        with:
          path: jahrik.zsh

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install ansible

      - name: Install Galaxy requirements
        run: ansible-galaxy install -r jahrik.zsh/requirements.yml -p ${{ github.workspace }}

      - name: Run converge
        working-directory: jahrik.zsh
        env:
          ANSIBLE_ROLES_PATH: ${{ github.workspace }}
        run: ansible-playbook molecule/localhost/converge.yml -i "localhost," -c local

      - name: Run verify
        working-directory: jahrik.zsh
        env:
          ANSIBLE_ROLES_PATH: ${{ github.workspace }}
        run: ansible-playbook molecule/localhost/verify.yml -i "localhost," -c local

  release:
    name: Release
    needs: [molecule, steamdeck, macos]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          git_branch: main
