---
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install linting dependencies
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .

  molecule:
    name: Molecule Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Molecule and dependencies
        run: |
          pip install molecule molecule-docker

      - name: Install Galaxy dependencies
        if: fileExists('requirements.yml')
        run: ansible-galaxy install -r requirements.yml

      - name: Run Molecule tests
        run: molecule test -d docker
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"

  release:
    name: Release to Galaxy
    needs:
      - molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Install Galaxy dependencies
        if: fileExists('requirements.yml')
        run: ansible-galaxy install -r requirements.yml

      - name: Publish Role to Ansible Galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
